services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    C4Y\Reviews\:
        resource: '../../*'
        exclude: '../../{Resources/contao,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
